<div>
    <div class="doc-heading-1">This is the test page for all the docs styles</div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer egestas turpis quis lorem molestie rutrum. Maecenas ac viverra purus, commodo ultrices augue. Sed porta urna diam, eget pellentesque dui mattis sed. Etiam in diam tempus, ultrices ante at, faucibus diam. Donec fermentum interdum elit, et auctor purus pulvinar non. Nam at felis lorem. Duis orci tellus, vulputate non quam sit amet, fermentum malesuada erat. Suspendisse sit amet metus felis.</p>
    
    <div class="doc-heading-2">another test but smaller</div>
    <p>Nulla urna sem, convallis at ullamcorper ac, eleifend a leo. Praesent vitae maximus risus. Duis a euismod magna. Aenean ut gravida urna, at varius dolor. Fusce a urna vel felis efficitur eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in pellentesque sapien. Curabitur sed sagittis ante.</p>
    
    <div class="doc-heading-3">smallest header possible</div>
    <p>Curabitur tempor mauris magna. Integer in rhoncus erat. Curabitur vel enim vel magna vehicula elementum eu quis nisl. Phasellus ut velit sed nibh mattis finibus eu sed eros. Aenean nec luctus nulla. Nulla non laoreet lorem, ut commodo arcu. Proin vel semper lectus, id commodo mi. Vestibulum quis augue id justo egestas elementum. In rhoncus sed diam at dignissim.</p>
    <p>Etiam tincidunt lorem vel dui interdum egestas. Praesent at rutrum felis, id ullamcorper erat. Nunc nunc magna, porta dignissim malesuada sed, fringilla non massa. Proin dui ante, dapibus et dictum id, auctor sed felis. Duis nec egestas ante, consectetur sagittis arcu. Duis consectetur mollis vulputate. Cras sed sem sit amet libero aliquam pulvinar sed eu leo. Curabitur aliquam diam quam, vel gravida lorem placerat ut. Integer sollicitudin a tortor ut feugiat. Morbi sed feugiat risus, vel aliquet turpis. Nullam congue, augue in malesuada tempor, purus sem blandit lacus, sit amet lacinia nisl velit eget mi. Etiam eget elit vel magna porta elementum eu non nisi. Nulla interdum erat eget mauris ultrices, nec tincidunt quam tempus. Phasellus pellentesque arcu quis turpis efficitur convallis. Nam elit risus, hendrerit rhoncus vehicula eget, interdum at ex.</p>

    <div class="doc-heading-3">smallest header possible</div>
    <p>Curabitur tempor mauris magna. Integer in rhoncus erat. Curabitur vel enim vel magna vehicula elementum eu quis nisl. Phasellus ut velit sed nibh mattis finibus eu sed eros. Aenean nec luctus nulla. Nulla non laoreet lorem, ut commodo arcu. Proin vel semper lectus, id commodo mi. Vestibulum quis augue id justo egestas elementum. In rhoncus sed diam at dignissim.</p>
    <p>Etiam tincidunt lorem vel dui interdum egestas. Praesent at rutrum felis, id ullamcorper erat. Nunc nunc magna, porta dignissim malesuada sed, fringilla non massa. Proin dui ante, dapibus et dictum id, auctor sed felis. Duis nec egestas ante, consectetur sagittis arcu. Duis consectetur mollis vulputate. Cras sed sem sit amet libero aliquam pulvinar sed eu leo. Curabitur aliquam diam quam, vel gravida lorem placerat ut. Integer sollicitudin a tortor ut feugiat. Morbi sed feugiat risus, vel aliquet turpis. Nullam congue, augue in malesuada tempor, purus sem blandit lacus, sit amet lacinia nisl velit eget mi. Etiam eget elit vel magna porta elementum eu non nisi. Nulla interdum erat eget mauris ultrices, nec tincidunt quam tempus. Phasellus pellentesque arcu quis turpis efficitur convallis. Nam elit risus, hendrerit rhoncus vehicula eget, interdum at ex.</p>

    <div class="doc-heading-3">smallest header possible</div>
    <p>Curabitur tempor mauris magna. Integer in rhoncus erat. Curabitur vel enim vel magna vehicula elementum eu quis nisl. Phasellus ut velit sed nibh mattis finibus eu sed eros. Aenean nec luctus nulla. Nulla non laoreet lorem, ut commodo arcu. Proin vel semper lectus, id commodo mi. Vestibulum quis augue id justo egestas elementum. In rhoncus sed diam at dignissim.</p>
    <p>Etiam tincidunt lorem vel dui interdum egestas. Praesent at rutrum felis, id ullamcorper erat. Nunc nunc magna, porta dignissim malesuada sed, fringilla non massa. Proin dui ante, dapibus et dictum id, auctor sed felis. Duis nec egestas ante, consectetur sagittis arcu. Duis consectetur mollis vulputate. Cras sed sem sit amet libero aliquam pulvinar sed eu leo. Curabitur aliquam diam quam, vel gravida lorem placerat ut. Integer sollicitudin a tortor ut feugiat. Morbi sed feugiat risus, vel aliquet turpis. Nullam congue, augue in malesuada tempor, purus sem blandit lacus, sit amet lacinia nisl velit eget mi. Etiam eget elit vel magna porta elementum eu non nisi. Nulla interdum erat eget mauris ultrices, nec tincidunt quam tempus. Phasellus pellentesque arcu quis turpis efficitur convallis. Nam elit risus, hendrerit rhoncus vehicula eget, interdum at ex.</p>

    <div class="doc-heading-1">This is the test page for all the docs styles</div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer egestas turpis quis lorem molestie rutrum. Maecenas ac viverra purus, commodo ultrices augue. Sed porta urna diam, eget pellentesque dui mattis sed. Etiam in diam tempus, ultrices ante at, faucibus diam. Donec fermentum interdum elit, et auctor purus pulvinar non. Nam at felis lorem. Duis orci tellus, vulputate non quam sit amet, fermentum malesuada erat. Suspendisse sit amet metus felis.</p>
    
</div>